### ISSUE TITLE
Add in json parsing ability

### ISSUE THREAD

**Issue by ericchen0121** [rgerard/node-sportsdata#10] opened 2015-01-22 07:20 UTC
SD's api just came out with .json support, so no more need for only xml parsing. I'd love to get this integrated into the package.

**Comment by rgerard** [comment] 2015-01-24 21:18
This is a dupe of https://github.com/rgerard/node-sportsdata/issues/11, so I'm closing this one.

**Closed as completed by rgerard** 2015-01-24 21:18 UTC
